In [1]:
print("hola mundo")

hola mundo

In [2]:
import numpy as np
import time

In [3]:
numeros = np.array([1,2,3,4])
print(f"Array : {numeros}")
print(f"tipo : {type(numeros)}")
print(f"tipo de datos:{numeros.dtype}")

Array : [1 2 3 4]
tipo : <class 'numpy.ndarray'>
tipo de datos:int64

In [4]:
valor = 10000
print("-----")
inicio = time.time()
listaArray = range(valor)
resultado = [i*2 for i in listaArray]
print(f"Lista = {time.time() - inicio:4f} seg.")
print("-----")
listaNumpy = np.array(valor)
resultado2 = listaNumpy*2
print(f"NumPy = {time.time() - inicio:4f} seg.")

-----
Lista = 0.000881 seg.
-----
NumPy = 0.001688 seg.

In [5]:
import numpy as np

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Dimensiones: {arr_2d.shape}")
print("Contenido de la matriz:")
print(arr_2d)

Dimensiones: (2, 3)
Contenido de la matriz:
[[1 2 3]
 [4 5 6]]

In [6]:
import numpy as np

# Definición del arreglo 3D
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

# Salida estructurada y limpia
print("="*30)
print("📊 REPORTE DE ESTRUCTURA NUMPY")
print("="*30)

# Información de dimensiones
print(f"🔹 Dimensiones (Shape): {arr_3d.shape}")
print(f"🔹 Rango (NDim):        {arr_3d.ndim}")
print(f"🔹 Total Elementos:     {arr_3d.size}")
print("-" * 30)

# Visualización del contenido
print("📦 CONTENIDO DEL ARREGLO:")
print(arr_3d)
print("="*30)

==============================
📊 REPORTE DE ESTRUCTURA NUMPY
==============================
🔹 Dimensiones (Shape): (2, 2, 2)
🔹 Rango (NDim):        3
🔹 Total Elementos:     8
------------------------------
📦 CONTENIDO DEL ARREGLO:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
==============================

In [17]:
a = np.array([1,2,3])
b = np.array([10,20,30])

print(f"a + b = {a+b}")
print(f"a * b = {a*b}")
print(f"a ** 2 = {a**2}")

print(f"sum(a)  = {np.sum(a)} -----  {np.sum(b)}")
print(f"mean(a) = {np.mean(a)} ----- {np.mean(b)}")
print(f"std(a)  = {np.std(a)} ----- {np.std(b)}")

a + b = [11 22 33]
a * b = [10 40 90]
a ** 2 = [1 4 9]
sum(a)  = 6 -----  60
mean(a) = 2.0 ----- 20.0
std(a)  = 0.816496580927726 ----- 8.16496580927726

In [18]:
import pandas as pd

In [25]:
data = {
    "nombre":["ana","carlos","maria"],
    "edad":[19,21,22],
    "ciudad":["Lima","Quito","Berlin"],
    "notas":[12,19,11],
    "universidad":["ulima","usil","uni"],
    "carrera":["sistema","industrial","contabilidad"]
}
df = pd.DataFrame(data)

In [26]:
print(df)

   nombre  edad  ciudad  notas universidad       carrera
0     ana    19    Lima     12       ulima       sistema
1  carlos    21   Quito     19        usil    industrial
2   maria    22  Berlin     11         uni  contabilidad

In [27]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   nombre       3 non-null      str
 1   edad         3 non-null      int64
 2   ciudad       3 non-null      str
 3   notas        3 non-null      int64
 4   universidad  3 non-null      str
 5   carrera      3 non-null      str
dtypes: int64(2), str(4)
memory usage: 276.0 bytes
None

In [29]:
print(f"\nColumnas : {df.columns.tolist()}")
print(f"\nForma : {df.shape}" )

Columnas : ['nombre', 'edad', 'ciudad', 'notas', 'universidad', 'carrera']

Forma : (3, 6)

In [31]:
print("Nombres : ", df["nombre"].tolist())

Nombres :  ['ana', 'carlos', 'maria']

In [34]:
print("\nPrimera fila")
print("-"*30)
print(df.loc[0])
print("-"*30)

Primera fila
------------------------------
nombre             ana
edad                19
ciudad            Lima
notas               12
universidad      ulima
carrera        sistema
Name: 0, dtype: object
------------------------------

In [35]:
print("\nPrimera fila")
print("-"*30)
print(df.iloc[0])
print("-"*30)

Primera fila
------------------------------
nombre             ana
edad                19
ciudad            Lima
notas               12
universidad      ulima
carrera        sistema
Name: 0, dtype: object
------------------------------

In [36]:
df

   nombre  edad  ciudad  notas universidad       carrera
0     ana    19    Lima     12       ulima       sistema
1  carlos    21   Quito     19        usil    industrial
2   maria    22  Berlin     11         uni  contabilidad

In [40]:
filterEdad =  df[df["edad"]<20]
print(filterEdad)

  nombre  edad ciudad  notas universidad  carrera
0    ana    19   Lima     12       ulima  sistema

In [41]:
#describe() da estadísticas
print(df.describe())

            edad      notas
count   3.000000   3.000000
mean   20.666667  14.000000
std     1.527525   4.358899
min    19.000000  11.000000
25%    20.000000  11.500000
50%    21.000000  12.000000
75%    21.500000  15.500000
max    22.000000  19.000000

In [42]:
data = pd.read_csv("../data/FL_insurance_sample.csv")

In [43]:
data

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36629,404309,FL,PINELLAS COUNTY,0.0,88722.00,0.0,88722.0,88722.00,155065.65,0.0,0.0,0.0,0,28.122885,-82.770218,Residential,Wood,3
36630,465875,FL,PINELLAS COUNTY,1297057.5,1297057.50,1297057.5,1297057.5,1297057.50,1577500.79,0.0,0.0,0.0,0,28.080900,-82.758800,Residential,Masonry,1
36631,791209,FL,PINELLAS COUNTY,173286.9,173286.90,0.0,0.0,173286.90,205527.97,0.0,0.0,0.0,0,28.110550,-82.766360,Residential,Wood,4
36632,322627,FL,PINELLAS COUNTY,1499781.6,1499781.60,0.0,0.0,1499781.60,1768782.43,0.0,0.0,0.0,0,28.089415,-82.697411,Residential,Masonry,3
36633,398149,FL,PINELLAS COUNTY,373488.3,373488.30,0.0,0.0,373488.30,596003.67,0.0,0.0,0.0,0,28.064440,-82.774590,Residential,Masonry,1

In [49]:
print("-"*30)
print(f"Columnas : {data.columns.tolist()}")
print("-"*30)
print(data.shape)
print("-"*30)
print(data.info())

------------------------------
Columnas : ['policyID', 'statecode', 'county', 'eq_site_limit', 'hu_site_limit', 'fl_site_limit', 'fr_site_limit', 'tiv_2011', 'tiv_2012', 'eq_site_deductible', 'hu_site_deductible', 'fl_site_deductible', 'fr_site_deductible', 'point_latitude', 'point_longitude', 'line', 'construction', 'point_granularity']
------------------------------
(36634, 18)
------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 36634 entries, 0 to 36633
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   policyID            36634 non-null  int64
 1   statecode           36634 non-null  str
 2   county              36634 non-null  str
 3   eq_site_limit       36634 non-null  float64
 4   hu_site_limit       36634 non-null  float64
 5   fl_site_limit       36634 non-null  float64
 6   fr_site_limit       36634 non-null  float64
 7   tiv_2011            36634 non-null  float64
 8   tiv_2012            36634 non-null  float64
 9   eq_site_deductible  36634 non-null  float64
 10  hu_site_deductible  36634 non-null  float64
 11  fl_site_deductible  36634 non-null  float64
 12  fr_site_deductible  36634 non-null  int64
 13  point_latitude      36634 non-null  float64
 14  point_longitude     36634 non-null  float64
 15  line                36634 non-null  str
 16  construction        36634 non-null  str
 17  point_granularity   36634 non-null  int64
dtypes: float64(11), int64(3), str(4)
memory usage: 5.0 MB
None

In [50]:
print("-"*30)
print(data.describe())

------------------------------
            policyID  eq_site_limit  hu_site_limit  fl_site_limit  \
count   36634.000000   3.663400e+04   3.663400e+04   3.663400e+04
mean   548661.937189   7.314780e+05   2.074348e+06   6.646009e+05
std    259912.926494   1.752300e+07   1.964150e+07   1.746114e+07
min    100074.000000   0.000000e+00   0.000000e+00   0.000000e+00
25%    323647.750000   0.000000e+00   4.248106e+04   0.000000e+00
50%    548525.000000   0.000000e+00   1.926911e+05   0.000000e+00
75%    774252.000000   0.000000e+00   9.163381e+05   0.000000e+00
max    999971.000000   2.160000e+09   2.160000e+09   2.160000e+09

       fr_site_limit      tiv_2011      tiv_2012  eq_site_deductible  \
count   3.663400e+04  3.663400e+04  3.663400e+04        3.663400e+04
mean    9.911724e+05  2.172875e+06  2.571004e+06        7.787908e+02
std     1.767178e+07  2.015015e+07  2.036777e+07        4.787979e+04
min     0.000000e+00  9.000000e+01  7.337000e+01        0.000000e+00
25%     0.000000e+00  4.562415e+04  5.401351e+04        0.000000e+00
50%     0.000000e+00  2.021051e+05  2.416310e+05        0.000000e+00
75%     5.741010e+04  9.465821e+05  1.128871e+06        0.000000e+00
max     2.160000e+09  2.160000e+09  1.701000e+09        6.273765e+06

       hu_site_deductible  fl_site_deductible  fr_site_deductible  \
count        3.663400e+04        36634.000000        36634.000000
mean         7.037985e+03          192.453210           26.483594
std          9.582593e+04         8037.713716         4702.740932
min          0.000000e+00            0.000000            0.000000
25%          0.000000e+00            0.000000            0.000000
50%          0.000000e+00            0.000000            0.000000
75%          0.000000e+00            0.000000            0.000000
max          7.380000e+06       450000.000000       900000.000000

       point_latitude  point_longitude  point_granularity
count    36634.000000     36634.000000       36634.000000
mean        28.087477       -81.903565           1.640907
std          1.647734         1.809066           1.070561
min         24.547514       -87.447290           1.000000
25%         26.471996       -82.439331           1.000000
50%         28.057077       -81.585700           1.000000
75%         29.623005       -80.372910           3.000000
max         30.989820       -80.033257           7.000000

In [51]:
data.head(5)

,policyID,statecode,county,eq_site_limit,hu_site_limit,fl_site_limit,fr_site_limit,tiv_2011,tiv_2012,eq_site_deductible,hu_site_deductible,fl_site_deductible,fr_site_deductible,point_latitude,point_longitude,line,construction,point_granularity
0,119736,FL,CLAY COUNTY,498960.0,498960.00,498960.0,498960.0,498960.00,792148.90,0.0,9979.2,0.0,0,30.102261,-81.711777,Residential,Masonry,1
1,448094,FL,CLAY COUNTY,1322376.3,1322376.30,1322376.3,1322376.3,1322376.30,1438163.57,0.0,0.0,0.0,0,30.063936,-81.707664,Residential,Masonry,3
2,206893,FL,CLAY COUNTY,190724.4,190724.40,190724.4,190724.4,190724.40,192476.78,0.0,0.0,0.0,0,30.089579,-81.700455,Residential,Wood,1
3,333743,FL,CLAY COUNTY,0.0,79520.76,0.0,0.0,79520.76,86854.48,0.0,0.0,0.0,0,30.063236,-81.707703,Residential,Wood,3
4,172534,FL,CLAY COUNTY,0.0,254281.50,0.0,254281.5,254281.50,246144.49,0.0,0.0,0.0,0,30.060614,-81.702675,Residential,Wood,1

In [2]:
import pandas as pd

In [ ]:
s = pd.Series([7])

In [4]:
print(s)

Series([], dtype: object)

--- 
## 📝 Summary (Cornell Notes)

1. **Core Concept:** Aplica siempre el rigor técnico a tus implementaciones.
2. **Buenas Prácticas:** Mantén tu código modular, tipado y documentado.
3. **Siguiente Paso:** Revisa los conceptos donde tuviste fricción cognitiva y refuérzalos.