In [2]:
import pandas as pd

In [3]:
url_CSV = 'https://www.football-data.co.uk/mmz4281/2122/E0.csv'
dataFrame = pd.read_csv(url_CSV)

In [4]:
dataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 380 entries, 0 to 379
Columns: 106 entries, Div to AvgCAHA
dtypes: float64(82), int64(16), object(8)
memory usage: 314.8+ KB

In [5]:
dataFrame.describe()

,FTHG,FTAG,HTHG,HTAG,HS,AS,HST,AST,HF,AF,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
count,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000,...,380.000000,380.000000,379.000000,379.000000,380.000000,380.000000,380.000000,380.000000,380.000000,380.000000
mean,1.513158,1.305263,0.681579,0.589474,13.847368,11.736842,4.678947,4.142105,10.055263,10.157895,...,2.070053,-0.248026,1.933193,1.966069,1.951105,1.975447,2.021211,2.054711,1.926868,1.958500
std,1.326545,1.258836,0.832187,0.808853,5.661784,5.348460,2.600402,2.589978,3.444180,3.718501,...,0.404372,0.950713,0.104168,0.099308,0.105294,0.106912,0.113965,0.111772,0.093221,0.094822
min,0.000000,0.000000,0.000000,0.000000,3.000000,1.000000,0.000000,0.000000,1.000000,2.000000,...,1.480000,-2.750000,1.650000,1.700000,1.660000,1.720000,1.800000,1.820000,1.700000,1.750000
25%,1.000000,0.000000,0.000000,0.000000,9.000000,8.000000,3.000000,2.000000,8.000000,7.000000,...,1.780000,-0.750000,1.855000,1.900000,1.870000,1.907500,1.940000,1.960000,1.850000,1.890000
50%,1.000000,1.000000,0.000000,0.000000,13.500000,11.000000,4.000000,4.000000,10.000000,10.000000,...,1.990000,-0.250000,1.940000,1.970000,1.950000,1.970000,2.010000,2.050000,1.925000,1.955000
75%,2.000000,2.000000,1.000000,1.000000,17.000000,15.000000,6.000000,6.000000,12.000000,12.250000,...,2.230000,0.250000,2.020000,2.050000,2.020000,2.050000,2.100000,2.140000,2.000000,2.040000
max,7.000000,6.000000,4.000000,4.000000,31.000000,31.000000,15.000000,14.000000,22.000000,25.000000,...,3.780000,2.500000,2.150000,2.200000,2.260000,2.380000,2.850000,2.520000,2.150000,2.230000

In [6]:
dataFrame.columns

Index(['Div', 'Date', 'Time', 'HomeTeam', 'AwayTeam', 'FTHG', 'FTAG', 'FTR',
       'HTHG', 'HTAG',
       ...
       'AvgC<2.5', 'AHCh', 'B365CAHH', 'B365CAHA', 'PCAHH', 'PCAHA', 'MaxCAHH',
       'MaxCAHA', 'AvgCAHH', 'AvgCAHA'],
      dtype='object', length=106)

In [7]:
dataFrame

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [8]:
dataFrame = dataFrame.rename(columns={'Date':'Fecha','HomeTeam' : 'home_team','AwayTeam':'away_Team' ,'FTHG':'home_goals','FTAG':'away_goals' })

In [9]:
dataFrame

,Div,Fecha,Time,home_team,away_Team,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89

In [10]:
# crear una variable root
root = "https://www.football-data.co.uk/mmz4281/"

In [11]:
root

'https://www.football-data.co.uk/mmz4281/'

In [12]:
leagues = ['E0','E2','E3']
frames = []

for league in leagues:
    df = pd.read_csv(root+'2122'+'/'+league+'.csv')
    frames.append(df)

len(frames)

3

In [13]:
frames[2].head(3)

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,07/08/2021,15:00,Carlisle,Colchester,0,0,D,0,0,...,1.57,-0.25,1.75,2.05,1.78,2.13,1.82,2.13,1.75,2.08
1,E3,07/08/2021,15:00,Exeter,Bradford,0,0,D,0,0,...,1.65,0.00,1.80,2.05,1.79,2.12,1.87,2.12,1.80,2.03
2,E3,07/08/2021,15:00,Forest Green,Sutton,2,1,H,1,0,...,1.60,-0.25,1.98,1.83,1.93,1.95,2.03,1.99,1.91,1.90

In [14]:
leagues = ['E0','E2', 'E3']

frames = []

# hacer loop a un rango de temporadas e insertar una nueva columna
for league in leagues:
    for season in range(15,21): # rango de temporadas
        url = root + str(season) + str(season+1) + "/" + league + ".csv"
        print(url)
        df = pd.read_csv(url)
        df.insert(1, 'season', season)
        frames.append(df)

https://www.football-data.co.uk/mmz4281/1516/E0.csv
https://www.football-data.co.uk/mmz4281/1617/E0.csv
https://www.football-data.co.uk/mmz4281/1718/E0.csv
https://www.football-data.co.uk/mmz4281/1819/E0.csv
https://www.football-data.co.uk/mmz4281/1920/E0.csv
https://www.football-data.co.uk/mmz4281/2021/E0.csv
https://www.football-data.co.uk/mmz4281/1516/E2.csv
https://www.football-data.co.uk/mmz4281/1617/E2.csv
https://www.football-data.co.uk/mmz4281/1718/E2.csv
https://www.football-data.co.uk/mmz4281/1819/E2.csv
https://www.football-data.co.uk/mmz4281/1920/E2.csv
https://www.football-data.co.uk/mmz4281/2021/E2.csv
https://www.football-data.co.uk/mmz4281/1516/E3.csv
https://www.football-data.co.uk/mmz4281/1617/E3.csv
https://www.football-data.co.uk/mmz4281/1718/E3.csv
https://www.football-data.co.uk/mmz4281/1819/E3.csv
https://www.football-data.co.uk/mmz4281/1920/E3.csv
https://www.football-data.co.uk/mmz4281/2021/E3.csv

In [15]:
frames[17]

,Div,season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E3,20,12/09/2020,15:00,Barrow,Stevenage,1,1,D,1,...,1.76,-0.25,1.95,1.90,1.93,1.98,1.98,1.99,1.91,1.92
1,E3,20,12/09/2020,15:00,Bolton,Forest Green,0,1,A,0,...,1.79,-0.25,2.02,1.83,2.04,1.87,2.09,1.90,2.00,1.83
2,E3,20,12/09/2020,15:00,Bradford,Colchester,0,0,D,0,...,1.65,-0.25,2.07,1.72,2.11,1.82,2.20,1.82,2.09,1.76
3,E3,20,12/09/2020,15:00,Cambridge,Carlisle,3,0,H,2,...,1.70,-0.25,1.98,1.88,2.02,1.88,2.04,1.90,1.99,1.84
4,E3,20,12/09/2020,15:00,Cheltenham,Morecambe,1,2,A,1,...,1.75,-0.50,1.83,2.02,1.87,2.04,1.88,2.09,1.83,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,E3,20,08/05/2021,15:00,Port Vale,Mansfield,0,3,A,0,...,1.84,0.25,1.90,1.95,1.89,2.00,1.95,2.07,1.85,1.97
548,E3,20,08/05/2021,15:00,Scunthorpe,Stevenage,0,1,A,0,...,1.73,0.50,1.80,2.05,1.84,2.06,1.87,2.14,1.77,2.07
549,E3,20,08/05/2021,15:00,Southend,Newport County,1,1,D,1,...,1.44,0.50,1.93,1.93,1.94,1.94,1.97,1.97,1.91,1.91
550,E3,20,08/05/2021,15:00,Tranmere,Colchester,0,0,D,0,...,1.59,-0.75,2.05,1.80,2.05,1.85,2.08,1.89,2.01,1.82
551,E3,20,08/05/2021,16:00,Salford,Leyton Orient,3,0,H,1,...,1.87,-1.00,1.98,1.88,1.99,1.90,2.01,1.96,1.96,1.86

In [16]:
dataFrame2 = pd.DataFrame(frames[0])

In [17]:
dataFrame2

,Div,season,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,BbAv<2.5,BbAH,BbAHh,BbMxAHH,BbAvAHH,BbMxAHA,BbAvAHA,PSCH,PSCD,PSCA
0,E0,15,08/08/2015,Bournemouth,Aston Villa,0,1,A,0,0,...,1.79,26,-0.50,1.98,1.93,1.99,1.92,1.82,3.88,4.70
1,E0,15,08/08/2015,Chelsea,Swansea,2,2,D,2,1,...,1.99,27,-1.50,2.24,2.16,1.80,1.73,1.37,5.04,10.88
2,E0,15,08/08/2015,Everton,Watford,2,2,D,0,1,...,1.96,26,-1.00,2.28,2.18,1.76,1.71,1.75,3.76,5.44
3,E0,15,08/08/2015,Leicester,Sunderland,4,2,H,3,0,...,1.67,26,-0.50,2.00,1.95,1.96,1.90,1.79,3.74,5.10
4,E0,15,08/08/2015,Man United,Tottenham,1,0,H,1,0,...,2.01,26,-1.00,2.20,2.09,1.82,1.78,1.64,4.07,6.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,15,15/05/2016,Stoke,West Ham,2,1,H,0,1,...,2.27,30,0.25,2.11,2.03,1.87,1.83,3.05,4.00,2.26
376,E0,15,15/05/2016,Swansea,Man City,1,1,D,1,1,...,2.45,31,1.00,2.14,2.05,1.85,1.81,7.05,5.00,1.47
377,E0,15,15/05/2016,Watford,Sunderland,2,2,D,0,1,...,2.10,29,-0.50,2.06,2.01,1.91,1.85,1.64,4.52,5.27
378,E0,15,15/05/2016,West Brom,Liverpool,1,1,D,1,1,...,2.09,30,-0.25,2.10,2.05,1.86,1.81,2.61,3.75,2.70
379,E0,15,17/05/2016,Man United,Bournemouth,3,1,H,1,0,...,2.20,29,-0.75,1.88,1.84,2.08,2.02,1.50,4.60,7.03

In [18]:
print(frames)

[    Div  season        Date     HomeTeam     AwayTeam  FTHG  FTAG FTR  HTHG  \
0    E0      15  08/08/2015  Bournemouth  Aston Villa     0     1   A     0
1    E0      15  08/08/2015      Chelsea      Swansea     2     2   D     2
2    E0      15  08/08/2015      Everton      Watford     2     2   D     0
3    E0      15  08/08/2015    Leicester   Sunderland     4     2   H     3
4    E0      15  08/08/2015   Man United    Tottenham     1     0   H     1
..   ..     ...         ...          ...          ...   ...   ...  ..   ...
375  E0      15  15/05/2016        Stoke     West Ham     2     1   H     0
376  E0      15  15/05/2016      Swansea     Man City     1     1   D     1
377  E0      15  15/05/2016      Watford   Sunderland     2     2   D     0
378  E0      15  15/05/2016    West Brom    Liverpool     1     1   D     1
379  E0      15  17/05/2016   Man United  Bournemouth     3     1   H     1

     HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  PSCH  \
0       0  ...     1.79   26  -0.50     1.98     1.93     1.99     1.92  1.82
1       1  ...     1.99   27  -1.50     2.24     2.16     1.80     1.73  1.37
2       1  ...     1.96   26  -1.00     2.28     2.18     1.76     1.71  1.75
3       0  ...     1.67   26  -0.50     2.00     1.95     1.96     1.90  1.79
4       0  ...     2.01   26  -1.00     2.20     2.09     1.82     1.78  1.64
..    ...  ...      ...  ...    ...      ...      ...      ...      ...   ...
375     1  ...     2.27   30   0.25     2.11     2.03     1.87     1.83  3.05
376     1  ...     2.45   31   1.00     2.14     2.05     1.85     1.81  7.05
377     1  ...     2.10   29  -0.50     2.06     2.01     1.91     1.85  1.64
378     1  ...     2.09   30  -0.25     2.10     2.05     1.86     1.81  2.61
379     0  ...     2.20   29  -0.75     1.88     1.84     2.08     2.02  1.50

     PSCD   PSCA
0    3.88   4.70
1    5.04  10.88
2    3.76   5.44
3    3.74   5.10
4    4.07   6.04
..    ...    ...
375  4.00   2.26
376  5.00   1.47
377  4.52   5.27
378  3.75   2.70
379  4.60   7.03

[380 rows x 66 columns],     Div  season      Date        HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0    E0      16  13/08/16         Burnley         Swansea     0     1   A
1    E0      16  13/08/16  Crystal Palace       West Brom     0     1   A
2    E0      16  13/08/16         Everton       Tottenham     1     1   D
3    E0      16  13/08/16            Hull       Leicester     2     1   H
4    E0      16  13/08/16        Man City      Sunderland     2     1   H
..   ..     ...       ...             ...             ...   ...   ...  ..
375  E0      16  21/05/17       Liverpool   Middlesbrough     3     0   H
376  E0      16  21/05/17      Man United  Crystal Palace     2     0   H
377  E0      16  21/05/17     Southampton           Stoke     0     1   A
378  E0      16  21/05/17         Swansea       West Brom     2     1   H
379  E0      16  21/05/17         Watford        Man City     0     5   A

     HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
0       0     0  ...     1.61   32  -0.25     2.13     2.06     1.86     1.81
1       0     0  ...     1.52   33  -0.50     2.07     2.00     1.90     1.85
2       1     0  ...     1.77   32   0.25     1.91     1.85     2.09     2.00
3       1     0  ...     1.67   31   0.25     2.35     2.26     2.03     1.67
4       1     0  ...     2.48   34  -1.50     1.81     1.73     2.20     2.14
..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
375     1     0  ...     2.73   18  -2.50     2.02     1.97     1.95     1.90
376     2     0  ...     1.81   19  -0.25     2.19     2.11     1.85     1.79
377     0     0  ...     2.01   18  -0.75     2.03     1.98     1.93     1.88
378     0     1  ...     1.98   19  -0.50     2.11     2.06     1.86     1.82
379     0     4  ...     2.80   18   1.75     1.99     1.94     2.00     1.93

      PSCH   PSCD   PSCA
0     2.79   3.16   2.89
1     2.25   3.15   3.86
2     3.64   3.54   2.16
3     4.68   3.50   1.92
4     1.25   6.50  14.50
..     ...    ...    ...
375   1.15  10.50  19.09
376   2.35   3.38   3.35
377   1.64   4.37   5.53
378   2.29   3.45   3.40
379  18.00   9.70   1.16

[380 rows x 66 columns],     Div  season        Date        HomeTeam      AwayTeam  FTHG  FTAG FTR  \
0    E0      17  11/08/2017         Arsenal     Leicester     4     3   H
1    E0      17  12/08/2017        Brighton      Man City     0     2   A
2    E0      17  12/08/2017         Chelsea       Burnley     2     3   A
3    E0      17  12/08/2017  Crystal Palace  Huddersfield     0     3   A
4    E0      17  12/08/2017         Everton         Stoke     1     0   H
..   ..     ...         ...             ...           ...   ...   ...  ..
375  E0      17  13/05/2018       Newcastle       Chelsea     3     0   H
376  E0      17  13/05/2018     Southampton      Man City     0     1   A
377  E0      17  13/05/2018         Swansea         Stoke     1     2   A
378  E0      17  13/05/2018       Tottenham     Leicester     5     4   H
379  E0      17  13/05/2018        West Ham       Everton     3     1   H

     HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
0       2     2  ...     2.32   21  -1.00     1.91     1.85     2.10     2.02
1       0     0  ...     2.27   20   1.50     1.95     1.91     2.01     1.96
2       0     3  ...     2.23   20  -1.75     2.03     1.97     1.95     1.90
3       0     2  ...     1.72   18  -0.75     2.10     2.05     1.86     1.83
4       1     0  ...     1.76   19  -0.75     1.94     1.90     2.01     1.98
..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
375     1     0  ...     2.01   21   1.00     1.90     1.83     2.11     2.03
376     0     0  ...     2.49   20   1.25     2.01     1.95     1.97     1.91
377     1     2  ...     2.06   19  -0.50     1.94     1.88     2.03     1.98
378     1     2  ...     2.84   20  -1.50     1.96     1.86     2.05     2.00
379     1     0  ...     1.97   21  -0.25     2.09     2.03     1.88     1.84

      PSCH  PSCD   PSCA
0     1.49  4.73   7.25
1    11.75  6.15   1.29
2     1.33  5.40  12.25
3     1.79  3.56   5.51
4     1.82  3.49   5.42
..     ...   ...    ...
375   4.85  3.72   1.80
376   6.32  4.78   1.51
377   2.08  3.56   3.82
378   1.38  5.50   8.15
379   2.35  3.40   3.28

[380 rows x 66 columns],     Div  season        Date      HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0    E0      18  10/08/2018    Man United       Leicester     2     1   H
1    E0      18  11/08/2018   Bournemouth         Cardiff     2     0   H
2    E0      18  11/08/2018        Fulham  Crystal Palace     0     2   A
3    E0      18  11/08/2018  Huddersfield         Chelsea     0     3   A
4    E0      18  11/08/2018     Newcastle       Tottenham     1     2   A
..   ..     ...         ...           ...             ...   ...   ...  ..
375  E0      18  12/05/2019     Liverpool          Wolves     2     0   H
376  E0      18  12/05/2019    Man United         Cardiff     0     2   A
377  E0      18  12/05/2019   Southampton    Huddersfield     1     1   D
378  E0      18  12/05/2019     Tottenham         Everton     2     2   D
379  E0      18  12/05/2019       Watford        West Ham     1     4   A

     HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
0       1     0  ...     1.79   17  -0.75     1.75     1.70     2.29     2.21
1       1     0  ...     1.83   20  -0.75     2.20     2.13     1.80     1.75
2       0     1  ...     1.87   22  -0.25     2.18     2.11     1.81     1.77
3       0     2  ...     1.84   23   1.00     1.84     1.80     2.13     2.06
4       1     2  ...     1.81   20   0.25     2.20     2.12     1.80     1.76
..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
375     1     0  ...     2.31   22  -1.50     1.98     1.91     2.01     1.95
376     0     1  ...     2.95   21  -2.00     2.52     2.32     1.72     1.64
377     1     0  ...     2.29   22  -1.50     2.27     2.16     1.80     1.73
378     1     0  ...     2.07   19  -0.50     2.13     2.08     1.85     1.80
379     0     2  ...     2.44   19  -0.50     2.25     2.19     1.78     1.72

     PSCH  PSCD  PSCA
0    1.55  4.07  7.69
1    1.88  3.61  4.70
2    2.62  3.38  2.90
3    7.24  3.95  1.58
4    4.74  3.53  1.89
..    ...   ...   ...
375  1.32  5.89  9.48
376  1.30  6.06  9.71
377  1.37  5.36  8.49
378  1.91  3.81  4.15
379  2.11  3.86  3.41

[380 rows x 63 columns],     Div  season        Date   Time        HomeTeam          AwayTeam  FTHG  \
0    E0      19  09/08/2019  20:00       Liverpool           Norwich     4
1    E0      19  10/08/2019  12:30        West Ham          Man City     0
2    E0      19  10/08/2019  15:00     Bournemouth  Sheffield United     1
3    E0      19  10/08/2019  15:00         Burnley       Southampton     3
4    E0      19  10/08/2019  15:00  Crystal Palace           Everton     0
..   ..     ...         ...    ...             ...               ...   ...
375  E0      19  26/07/2020  16:00       Leicester        Man United     0
376  E0      19  26/07/2020  16:00        Man City           Norwich     5
377  E0      19  26/07/2020  16:00       Newcastle         Liverpool     1
378  E0      19  26/07/2020  16:00     Southampton  Sheffield United     3
379  E0      19  26/07/2020  16:00        West Ham       Aston Villa     1

     FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
0       1   H     4  ...      3.43 -2.25     1.91      1.99   1.94   1.98
1       5   A     0  ...      2.91  1.75     1.95      1.95   1.96   1.97
2       1   D     0  ...      1.92 -0.50     1.95      1.95   1.98   1.95
3       0   H     0  ...      1.71  0.00     1.87      2.03   1.89   2.03
4       0   D     0  ...      1.71  0.25     1.82      2.08   1.97   1.96
..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
375     2   A     0  ...      2.03  0.50     1.89      2.01   1.88   2.05
376     0   H     2  ...      5.77 -3.75     2.03      1.87   2.01   1.88
377     3   A     1  ...      2.40  1.00     1.94      1.96   1.95   1.97
378     1   H     0  ...      2.01 -0.50     1.97      1.93   2.00   1.93
379     1   D     0  ...      2.03  0.00     1.93      1.97   1.95   1.98

     MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
0       1.99     2.07     1.90     1.99
1       2.07     1.98     1.97     1.92
2       2.00     1.96     1.96     1.92
3       1.90     2.07     1.86     2.02
4       2.03     2.08     1.96     1.93
..       ...      ...      ...      ...
375     1.94     2.05     1.86     2.02
376     2.06     1.88     2.02     1.84
377     2.03     2.00     1.95     1.92
378     2.03     1.96     1.98     1.89
379     1.99     2.00     1.93     1.95

[380 rows x 107 columns],     Div  season        Date   Time          HomeTeam        AwayTeam  FTHG  \
0    E0      20  12/09/2020  12:30            Fulham         Arsenal     0
1    E0      20  12/09/2020  15:00    Crystal Palace     Southampton     1
2    E0      20  12/09/2020  17:30         Liverpool           Leeds     4
3    E0      20  12/09/2020  20:00          West Ham       Newcastle     0
4    E0      20  13/09/2020  14:00         West Brom       Leicester     0
..   ..     ...         ...    ...               ...             ...   ...
375  E0      20  23/05/2021  16:00         Liverpool  Crystal Palace     2
376  E0      20  23/05/2021  16:00          Man City         Everton     5
377  E0      20  23/05/2021  16:00  Sheffield United         Burnley     1
378  E0      20  23/05/2021  16:00          West Ham     Southampton     3
379  E0      20  23/05/2021  16:00            Wolves      Man United     1

     FTAG FTR  HTHG  ...  AvgC<2.5  AHCh B365CAHH  B365CAHA  PCAHH  PCAHA  \
0       3   A     0  ...      1.84  0.75     2.01      1.89   2.02   1.91
1       0   H     1  ...      1.70  0.25     1.78      2.13   1.79   2.17
2       3   H     3  ...      2.62 -1.50     1.85      2.05   1.85   2.08
3       2   A     0  ...      1.92 -0.50     2.03      1.87   2.04   1.88
4       3   A     0  ...      1.73  0.25     1.92      1.98   1.93   1.99
..    ...  ..   ...  ...       ...   ...      ...       ...    ...    ...
375     0   H     1  ...      3.49 -2.25     1.86      2.04   1.88   2.03
376     0   H     2  ...      2.77 -1.75     2.01      1.89   1.99   1.89
377     0   H     1  ...      2.05  0.00     2.04      1.86   2.05   1.86
378     0   H     2  ...      2.14 -0.75     2.00      1.90   2.02   1.91
379     2   A     1  ...      1.62 -0.25     2.04      1.86   2.10   1.84

     MaxCAHH  MaxCAHA  AvgCAHH  AvgCAHA
0       2.13     1.92     2.02     1.87
1       1.85     2.18     1.79     2.12
2       1.90     2.16     1.84     2.04
3       2.09     1.91     2.02     1.86
4       1.95     2.01     1.91     1.97
..       ...      ...      ...      ...
375     1.98     2.14     1.88     2.00
376     2.20     2.00     2.03     1.85
377     2.17     1.90     2.03     1.84
378     2.06     2.01     1.99     1.89
379     2.10     1.94     2.00     1.88

[380 rows x 107 columns],      Div  season      Date          HomeTeam    AwayTeam  FTHG  FTAG  FTR  \
0     E2      15  08/08/15            Burton  Scunthorpe   2.0   1.0    H
1     E2      15  08/08/15      Chesterfield    Barnsley   3.0   1.0    H
2     E2      15  08/08/15        Colchester   Blackpool   2.0   2.0    D
3     E2      15  08/08/15          Coventry       Wigan   2.0   0.0    H
4     E2      15  08/08/15             Crewe   Port Vale   0.0   0.0    D
..   ...     ...       ...               ...         ...   ...   ...  ...
548   E2      15  08/05/16         Port Vale     Walsall   0.0   5.0    A
549   E2      15  08/05/16  Sheffield United  Scunthorpe   0.0   2.0    A
550   E2      15  08/05/16           Swindon  Shrewsbury   3.0   0.0    H
551   E2      15  08/05/16             Wigan    Barnsley   1.0   4.0    A
552  NaN      15       NaN               NaN         NaN   NaN   NaN  NaN

     HTHG  HTAG  ... BbAv<2.5  BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  \
0     0.0   0.0  ...     1.74  25.0  -0.25     1.99     1.93     1.94
1     0.0   1.0  ...     1.75  25.0  -0.25     1.93     1.87     2.02
2     1.0   2.0  ...     1.77  25.0  -0.25     1.94     1.88     2.01
3     1.0   0.0  ...     1.64  25.0   0.25     1.85     1.78     2.12
4     0.0   0.0  ...     1.75  23.0  -0.25     2.22     2.13     1.76
..    ...   ...  ...      ...   ...    ...      ...      ...      ...
548   0.0   3.0  ...     1.96  26.0   0.75     1.74     1.69     2.29
549   0.0   1.0  ...     2.06  27.0   0.25     1.93     1.86     2.02
550   1.0   0.0  ...     2.22  27.0  -0.25     2.00     1.93     1.96
551   1.0   2.0  ...     2.00  27.0  -0.25     2.08     2.01     1.87
552   NaN   NaN  ...      NaN   NaN    NaN      NaN      NaN      NaN

     BbAvAHA  PSCH  PSCD  PSCA
0       1.88  2.40  3.38  3.19
1       1.94  2.02  3.60  3.96
2       1.93  2.28  3.51  3.31
3       2.05  2.92  3.31  2.63
4       1.72  3.05  3.51  2.43
..       ...   ...   ...   ...
548     2.19  4.19  3.94  1.88
549     1.96  3.17  3.80  2.24
550     1.89  2.21  3.68  3.32
551     1.82  2.32  3.85  2.99
552      NaN   NaN   NaN   NaN

[553 rows x 66 columns],     Div  season      Date          HomeTeam            AwayTeam  FTHG  FTAG  \
0    E2      16  06/08/16            Bolton    Sheffield United     1     0
1    E2      16  06/08/16          Bradford           Port Vale     0     0
2    E2      16  06/08/16              Bury            Charlton     2     0
3    E2      16  06/08/16          Millwall              Oldham     3     0
4    E2      16  06/08/16       Northampton      Fleetwood Town     1     1
..   ..     ...       ...               ...                 ...   ...   ...
547  E2      16  30/04/17          Rochdale            Bradford     1     1
548  E2      16  30/04/17        Scunthorpe            Coventry     3     1
549  E2      16  30/04/17  Sheffield United        Chesterfield     3     2
550  E2      16  30/04/17          Southend                Bury     1     0
551  E2      16  30/04/17           Walsall  Milton Keynes Dons     1     4

    FTR  HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  \
0     H     1     0  ...     1.68   28   0.00     2.08     2.00     1.87
1     D     0     0  ...     1.68   29  -0.75     1.97     1.91     1.96
2     H     0     0  ...     1.74   29   0.25     1.80     1.74     2.20
3     H     2     0  ...     1.80   29  -0.75     1.85     1.80     2.10
4     D     1     0  ...     1.67   29  -0.25     2.00     1.91     1.99
..   ..   ...   ...  ...      ...  ...    ...      ...      ...      ...
547   D     0     1  ...     2.08   20  -0.25     2.00     1.94     1.95
548   H     0     1  ...     1.93   18  -1.00     2.13     2.02     1.86
549   H     1     1  ...     2.94   18  -2.00     1.95     1.88     2.01
550   H     1     0  ...     2.03   18  -0.75     2.01     1.96     1.95
551   A     0     2  ...     1.90   16   0.00     2.10     2.06     1.84

     BbAvAHA  PSCH  PSCD   PSCA
0       1.81  3.20  3.35   2.41
1       1.91  1.78  3.59   5.45
2       2.11  2.73  3.41   2.73
3       2.03  1.55  4.22   7.05
4       1.91  2.28  3.37   3.46
..       ...   ...   ...    ...
547     1.90  1.81  3.85   4.70
548     1.81  1.64  4.29   5.52
549     1.95  1.20  7.90  15.00
550     1.88  1.78  3.89   4.86
551     1.81  3.21  3.66   2.27

[552 rows x 66 columns],     Div  season      Date        HomeTeam            AwayTeam  FTHG  FTAG FTR  \
0    E2      17  05/08/17        Bradford           Blackpool     2     1   H
1    E2      17  05/08/17            Bury             Walsall     1     0   H
2    E2      17  05/08/17        Charlton         Bristol Rvs     1     0   H
3    E2      17  05/08/17       Doncaster          Gillingham     0     0   D
4    E2      17  05/08/17  Fleetwood Town           Rotherham     2     0   H
..   ..     ...       ...             ...                 ...   ...   ...  ..
547  E2      17  05/05/18        Rochdale            Charlton     1     0   H
548  E2      17  05/05/18       Rotherham           Blackpool     1     0   H
549  E2      17  05/05/18      Scunthorpe            Bradford     1     1   D
550  E2      17  05/05/18      Shrewsbury  Milton Keynes Dons     0     1   A
551  E2      17  05/05/18        Southend         Bristol Rvs     0     0   D

     HTHG  HTAG  ... BbAv<2.5 BbAH  BbAHh  BbMxAHH  BbAvAHH  BbMxAHA  BbAvAHA  \
0       1     1  ...     1.64   16  -0.75     1.86     1.81     2.08     2.04
1       1     0  ...     1.79   16  -0.50     2.09     2.03     1.87     1.82
2       1     0  ...     1.89   16  -0.25     2.07     2.02     1.89     1.83
3       0     0  ...     1.88   16  -0.50     1.83     1.79     2.11     2.06
4       1     0  ...     1.75   16  -0.25     2.00     1.94     1.98     1.91
..    ...   ...  ...      ...  ...    ...      ...      ...      ...      ...
547     0     0  ...     1.73   18  -0.25     1.86     1.81     2.06     2.01
548     0     0  ...     1.91   18  -0.25     2.20     2.11     1.80     1.74
549     0     0  ...     1.81   18  -0.50     1.93     1.86     2.01     1.96
550     0     0  ...     1.77   17  -0.75     2.12     2.03     1.84     1.80
551     0     0  ...     1.98   19  -0.25     2.03     1.95     1.95     1.87

     PSCH  PSCD  PSCA
0    1.69  3.97  5.50
1    2.02  3.55  4.03
2    2.19  3.66  3.39
3    1.69  3.96  5.45
4    2.20  3.38  3.66
..    ...   ...   ...
547  1.92  3.89  3.98
548  2.14  3.79  3.34
549  1.92  3.68  4.21
550  1.76  3.84  4.98
551  2.23  3.78  3.16

[552 rows x 66 columns],     Div  season        Date        HomeTeam        AwayTeam  FTHG  FTAG FTR  \
0    E2      18  04/08/2018      Accrington      Gillingham     0     2   A
1    E2      18  04/08/2018        Barnsley          Oxford     4     0   H
2    E2      18  04/08/2018          Burton        Rochdale     1     2   A

In [19]:
dict_countries = {
              'Spanish La Liga':'SP1', 'Spanish Segunda Division':'SP2',
              'German Bundesliga':'D1', 
              'English Premier League':'E0', 'English League 1':'E2', 'English League 2':'E3',
             }

In [20]:
dict_countries

{'Spanish La Liga': 'SP1',
 'Spanish Segunda Division': 'SP2',
 'German Bundesliga': 'D1',
 'English Premier League': 'E0',
 'English League 1': 'E2',
 'English League 2': 'E3'}

In [21]:
print(dict_countries['Spanish La Liga'],
      dict_countries['Spanish Segunda Division'],
      dict_countries['German Bundesliga'],
      dict_countries['English Premier League'],
      dict_countries['English League 1'],
      dict_countries['English League 2'])

SP1 SP2 D1 E0 E2 E3

In [22]:
dict_historical_data = {}

In [23]:
for league in dict_countries:
    frames=[]
    print(league)
    for season in range(15,21):
        url = root+str(season)+str(season+1)+'/' + dict_countries[league]+'.csv'
        dataframe = pd.read_csv(url)
        frames.append(dataFrame)
    
    df_frames = pd.concat(frames)
    dict_historical_data[league] = df_frames

Spanish La Liga
Spanish Segunda Division
German Bundesliga
English Premier League
English League 1
English League 2

In [24]:
dict_historical_data['Spanish La Liga']

,Div,Fecha,Time,home_team,away_Team,home_goals,away_goals,FTR,HTHG,HTAG,...,AvgC<2.5,AHCh,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA
0,E0,13/08/2021,20:00,Brentford,Arsenal,2,0,H,1,0,...,1.62,0.50,1.75,2.05,1.81,2.13,2.05,2.17,1.80,2.09
1,E0,14/08/2021,12:30,Man United,Leeds,5,1,H,1,0,...,2.25,-1.00,2.05,1.75,2.17,1.77,2.19,1.93,2.10,1.79
2,E0,14/08/2021,15:00,Burnley,Brighton,1,2,A,1,0,...,1.62,0.25,1.79,2.15,1.81,2.14,1.82,2.19,1.79,2.12
3,E0,14/08/2021,15:00,Chelsea,Crystal Palace,3,0,H,2,0,...,1.94,-1.50,2.05,1.75,2.12,1.81,2.16,1.93,2.06,1.82
4,E0,14/08/2021,15:00,Everton,Southampton,3,1,H,0,1,...,1.67,-0.50,2.05,1.88,2.05,1.88,2.08,1.90,2.03,1.86
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,E0,22/05/2022,16:00,Crystal Palace,Man United,1,0,H,1,0,...,2.04,0.25,1.68,2.15,1.74,2.23,1.88,2.25,1.74,2.16
376,E0,22/05/2022,16:00,Leicester,Southampton,4,1,H,0,0,...,2.63,-0.75,1.83,2.07,1.88,2.03,1.94,2.26,1.87,2.01
377,E0,22/05/2022,16:00,Liverpool,Wolves,3,1,H,1,1,...,3.28,-2.50,2.02,1.77,2.06,1.83,2.19,1.99,2.07,1.80
378,E0,22/05/2022,16:00,Man City,Aston Villa,3,2,H,0,1,...,3.36,-2.25,2.06,1.84,2.05,1.86,2.09,2.03,2.01,1.87
379,E0,22/05/2022,16:00,Norwich,Tottenham,0,5,A,0,2,...,2.40,1.50,1.95,1.95,1.96,1.94,2.16,1.98,1.99,1.89