In [1]:
countries = ['United States', 'India', 'China', 'Brazil']

In [10]:
countries.append('Japon')

In [11]:
print(countries)

['United States', 'India', 'China', 'Brazil', 'Russia', 'puerto rico', 'Argentina', 'Peru', 'Japon']

In [16]:
countries.remove('Brazil')

In [17]:
print(countries)

['United States', 'India', 'Russia', 'puerto rico', 'Argentina', 'Peru']

In [18]:
numbers = [4,3,10,7,1,2]

In [20]:
numbers.sort()

In [21]:
numbers

[1, 2, 3, 4, 7, 10]

In [22]:
my_data = {'nombre':'Frank', 'edad':26}

In [23]:
print(my_data)

{'nombre': 'Frank', 'edad': 26}

In [24]:
my_data['estatura'] = 1.75

In [25]:
print(my_data)

{'nombre': 'Frank', 'edad': 26, 'estatura': 1.75}

In [30]:
my_data.update({'peso':10,'leanguaje':'Python','leangue':['ingles','español']})

In [31]:
my_data

{'nombre': 'Frank',
 'edad': 26,
 'estatura': 1.75,
 'peso': 10,
 'leanguaje': 'Python',
 'leangue': ['ingles', 'español']}

In [32]:
xdata = my_data.copy()

In [33]:
print(xdata)

{'nombre': 'Frank', 'edad': 26, 'estatura': 1.75, 'peso': 10, 'leanguaje': 'Python', 'leangue': ['ingles', 'español']}

In [38]:
xdata.pop('leangue')

['ingles', 'español']

In [40]:
xdata

{'estatura': 1.75, 'peso': 10, 'leanguaje': 'python,sql'}

In [39]:
xdata.update({'leanguaje':'python,sql'})

In [41]:
xdata.pop('leanguaje')

'python,sql'

In [42]:
xdata

{'estatura': 1.75, 'peso': 10}

In [45]:
edad = 10
if edad < 18:
    print("Menor de edad")
elif edad >= 18 and edad < 65:
    print("Adulto")
else:
    print("Adulto mayor")

Menor de edad

In [3]:
for i in range(1,20,2):
    print(i)

1
3
5
7
9
11
13
15
17
19

In [4]:
def sumardosvalores(a,b):
    return a+b

In [5]:
sumardosvalores(5,10)

15

In [3]:
import pandas as pd
import numpy as np

In [4]:
peliculas = {
    'title':['Thunderbolts','Superman','Mickey 17'],
    'year':['2025','2023','2022'],
    'score':[4,2,3]

}

In [5]:
df = pd.DataFrame(peliculas)

In [6]:
df

          title  year  score
0  Thunderbolts  2025      4
1      Superman  2023      2
2     Mickey 17  2022      3

In [7]:
state = ['lima','Buenos Aires','Sucre ','Brasilia ']
population = [10000000,15000000,320000,3000000]

In [8]:
dict_americaSur = {
    'states' : state,
    'population':population
}

In [9]:
print(dict_americaSur)

{'states': ['lima', 'Buenos Aires', 'Sucre ', 'Brasilia '], 'population': [10000000, 15000000, 320000, 3000000]}

In [10]:
df_americaSur = pd.DataFrame(dict_americaSur)

In [11]:
print(df_americaSur)

         states  population
0          lima    10000000
1  Buenos Aires    15000000
2        Sucre       320000
3     Brasilia      3000000

In [12]:
df = pd.read_csv('StudentsPerformance.csv')

In [13]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [16]:
print(pd.__doc__)

pandas - a powerful data analysis and manipulation library for Python
=====================================================================

**pandas** is a Python package providing fast, flexible, and expressive data
structures designed to make working with "relational" or "labeled" data both
easy and intuitive. It aims to be the fundamental high-level building block for
doing practical, **real world** data analysis in Python. Additionally, it has
the broader goal of becoming **the most powerful and flexible open source data
analysis / manipulation tool available in any language**. It is already well on
its way toward this goal.

Main Features
-------------
Here are just a few of the things that pandas does well:

  - Easy handling of missing data in floating point as well as non-floating
    point data.
  - Size mutability: columns can be inserted and deleted from DataFrame and
    higher dimensional objects
  - Automatic and explicit data alignment: objects can be explicitly aligned
    to a set of labels, or the user can simply ignore the labels and let
    `Series`, `DataFrame`, etc. automatically align the data for you in
    computations.
  - Powerful, flexible group by functionality to perform split-apply-combine
    operations on data sets, for both aggregating and transforming data.
  - Make it easy to convert ragged, differently-indexed data in other Python
    and NumPy data structures into DataFrame objects.
  - Intelligent label-based slicing, fancy indexing, and subsetting of large
    data sets.
  - Intuitive merging and joining data sets.
  - Flexible reshaping and pivoting of data sets.
  - Hierarchical labeling of axes (possible to have multiple labels per tick).
  - Robust IO tools for loading data from flat files (CSV and delimited),
    Excel files, databases, and saving/loading data from the ultrafast HDF5
    format.
  - Time series-specific functionality: date range generation and frequency
    conversion, moving window statistics, date shifting and lagging.

In [18]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None